[workspace]
resolver = "2"

members = [
    "backend",
    "clients/src-tauri",
    "crates/crypto",
    "crates/dtos",
]

[workspace.dependencies]
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }
