[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
argon2 = "0.5.2"
async-trait = "0.1.75"
aws-config = "0.56.1"
aws-sdk-s3 = "0.31.2"
axum = { version = "0.6.20", features = ["multipart"] }
serde = { version = "1.0.193", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["runtime-tokio", "tls-native-tls", "postgres", "uuid", "time", "migrate"] }
thiserror = "1.0.52"
time = { version = "0.3.31", features = ["parsing", "serde"] }
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
tower-http = { version = "0.4.4", features = ["limit"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "serde"] }

[dev-dependencies]
anyhow = "1.0.77"
reqwest = { version = "0.11.23", features = ["multipart", "json"] }
