[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.55.2"
aws-sdk-s3 = "0.27.0"
axum = "0.6.18"
tokio = { version = "1.28.1", features = ["full"] }
