//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::FileState;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub state: FileState,
    pub created_at: TimeDateTimeWithTimeZone,
    pub added_at: TimeDateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub sha256: String,
    pub owner_id: Uuid,
    pub uploader_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub enc_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_users::Entity",
        from = "Column::OwnerId",
        to = "super::app_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppUsers2,
    #[sea_orm(
        belongs_to = "super::app_users::Entity",
        from = "Column::UploaderId",
        to = "super::app_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppUsers1,
}

impl ActiveModelBehavior for ActiveModel {}
