//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "file_state")]
pub enum FileState {
    #[sea_orm(string_value = "new")]
    New,
    #[sea_orm(string_value = "sync_in_progress")]
    SyncInProgress,
    #[sea_orm(string_value = "synced")]
    Synced,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "provider")]
pub enum Provider {
    #[sea_orm(string_value = "credentials")]
    Credentials,
}
