//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub private_key: String,
    #[sea_orm(column_type = "Text")]
    pub public_key: String,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_users::Entity",
        from = "Column::UserId",
        to = "super::app_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppUsers,
}

impl Related<super::app_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
