create table app_user
(
    id         bigint generated by default as identity (start with 1000) primary key,
    uuid       uuid        not null,
    username   text        not null unique,
    password   text        not null,
    created_at timestamptz not null default now()
);

create table auth_token
(
    id         bigint generated by default as identity (start with 1000) primary key,
    user_id    uuid        not null,
    token      text        not null unique,
    created_at timestamptz not null default now()
);

create table encryption_key
(
    id         bigint generated by default as identity (start with 1000) primary key,
    user_id    uuid        not null,
    key        text        not null,
    created_at timestamptz not null default now()
);

create type file_state as enum ('New', 'SyncInProgress', 'Synced');

create table file
(
    id          bigint generated by default as identity (start with 1000) primary key,
    path        text        not null,
    name        text        not null,
    state       file_state  not null,
    uuid        uuid        not null,
    created_at  timestamptz not null,
    added_at    timestamptz not null default now(),
    sha256      text        not null,
    owner_id    uuid        not null,
    uploader_id uuid        not null
);

