create table app_user
(
    id         bigint generated by default as identity (start with 1000) primary key,
    uuid       uuid        not null unique,
    name       text,
    created_at timestamptz not null default now()
);

create type provider as enum ('Credentials', 'Google');

create table user_account
(
    id         bigint generated by default as identity (start with 1000) primary key,
    user_id    uuid        not null,
    account_id text        not null,
    password   text,
    provider   provider    not null,
    created_at timestamptz not null default now()
);

alter table user_account
add constraint unique_username_provider unique (account_id, provider);

create table auth_token
(
    id         bigint generated by default as identity (start with 1000) primary key,
    user_id    uuid        not null,
    token      text        not null unique,
    created_at timestamptz not null default now()
);

create table authorization_requests
(
    id         bigint generated by default as identity (start with 1000) primary key,
    state      text        not null unique,
    pkce       text        not null unique,
    created_at timestamptz not null default now()
);

create table user_keys
(
    id              bigint generated by default as identity (start with 1000) primary key,
    user_id         uuid        not null,
    private_key     text        not null,
    public_key      text        not null,
    created_at      timestamptz not null default now()
);

create type file_state as enum ('New', 'SyncInProgress', 'Synced');

create table file
(
    id          bigint generated by default as identity (start with 1000) primary key,
    path        text        not null,
    name        text        not null,
    state       file_state  not null,
    uuid        uuid        not null,
    created_at  timestamptz not null,
    added_at    timestamptz not null default now(),
    sha256      text        not null,
    owner_id    uuid        not null,
    uploader_id uuid        not null,
    enc_key     text        not null
);

