create type file_state as enum ('New', 'SyncInProgress', 'Synced');

create table file (
    id bigint generated by default as identity (start with 1000) primary key,
    path text not null,
    name text not null,
    state file_state not null,
    uuid uuid not null,
    created_at timestamptz,
    added_at timestamptz not null default now(),
    sha256 text not null
);

